name: tech_blog_crawler

on:
  schedule:
    - cron : '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@2
    - name: Set up Python
      uses: actions/setup-python@2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [-f requirements.txt ]; then pip install -re requirements.txt; fi
    - name: Run main.py
      run: | 
        python main.py
      env:
        MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN}}